from views.about_window import AboutWindow
from views.ignored_folders_dialog import IgnoredFoldersDialog
from views.ui.ui_main_window import Ui_MainWindow
from views.main_window_view import MainWindow